import mongoose from 'mongoose';

const projectSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: true,
      trim: true,
    },
    description: {
      type: String,
    },
    goal: {
      type: String,
      required: true,
      description: 'The high-level project goal provided by the user',
    },
    owner: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    status: {
      type: String,
      enum: ['planning', 'in-progress', 'completed'],
      default: 'planning',
    },
    estimatedTimeline: {
      type: String,
      default: null,
    },
    aiSummary: {
      type: String,
      description: 'Summary generated by Gemini AI',
    },
    breakdown: {
      summary: String,
      keyMilestones: [String],
      riskFactors: [String],
      technologies: [String],
    },
    rootTasks: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Task',
      },
    ],
  },
  { timestamps: true }
);

const Project = mongoose.model('Project', projectSchema);
export default Project;
